[이찬우-teamA] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/38-backend-westagram pull request #10
Opened 2022-10-06 07:27 UTC by c0zyb1ue

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Express 초기 환경 설정
- TypeORM / dbConnection 설정
- dbmate 이용 test DB 생성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-06 08:23 UTC, sangwoong03 commented
schema.sql 파일은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

[추가사항]
- `.env.sample`와 공유가 필요한 환경변수 샘플 파일을 생성해주세요.
- `.gitignore` 파일을 생성하고  깃헙 상에서 공유가 되어선 안되는 파일을 관리해주세요.

2022-10-06 09:07 UTC, c0zyb1ue commented
수정 요청사항 수정 완료했습니다.

2022-10-06 09:10 UTC, SeongJoon-K requested changes

2022-10-06 09:10 UTC, SeongJoon-K commented on teamA/leeChanWoo/db/migrations/20221006063711_create_post.sql
> +DROP TABLE posts;
해당부분 줄바꿈을 지워주세요 ~! 
```suggestion
-- migrate:down
DROP TABLE posts;
```

2022-10-06 09:10 UTC, SeongJoon-K commented on teamA/leeChanWoo/db/migrations/20221006063903_create_likes.sql
> +
해당부분도 줄바꿈을 없애주세요 ~!
```suggestion
-- migrate:down
DROP TABLE likes;
```

2022-10-06 12:08 UTC, c0zyb1ue commented
줄바꿈 수정 완료했고, gitignore에서 schema.sql 파일 없애는 방법을 모르겠습니다.

2022-10-06 23:18 UTC, sangwoong03 commented
> 줄바꿈 수정 완료했고, gitignore에서 schema.sql 파일 없애는 방법을 모르겠습니다.

찬우님 git cache 삭제와 관련된 명령어가 있습니다.
`git rm -r --cached . ` 해당 부분을 찾아보고 명령어를 통해 적용해보세요!

2022-10-06 23:24 UTC, sangwoong03 commented on teamA/leeChanWoo/db/migrations/20221006063429_create_users.sql
> +		PRIMARY KEY(id)
해당 부분을 다른 migration 파일과 동일하게 들여쓰기 (Indentation)를 수정해주세요!
```suggestion
	id INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(200) NOT NULL,
	profile_image VARCHAR(1000) NULL,
	password VARCHAR(200) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
```

2022-10-06 23:24 UTC, sangwoong03 commented on teamA/leeChanWoo/db/migrations/20221006063931_create_comments.sql
> +  FOREIGN KEY (post_id) REFERENCES posts (id)
다른 개발자도 같은 프로젝트, 디렉토리를 공유하고 있기 때문에 코드 컨벤션을 지키는 것은 협업의 중요 요소 중 하나입니다.

들여쓰기 또한 코드의 가독성을 높이는 컨벤션 중 하나인데요,

코드 파일마다 tab size가 4칸, 2칸인 경우로 상이한 것 같습니다.

전부 수정해서 다시 올려주세요~!

2022-10-06 23:24 UTC, sangwoong03 commented on teamA/leeChanWoo/package.json
> +  }
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.
- mysql & mysql2 드라이버 패키지는 서로 동일한 기능을 하는 패키지 입니다. 따라서 둘 중 하나를 선택하여 설치를 진행해주세요.

```suggestion
  "dependencies": {
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.1",
    "mysql": "^2.18.1",
    "typeorm": "^0.3.10"
  },
  devDependencies: {
    "morgan": "^1.10.0",
    "nodemon": "^2.0.20"
  }
```

2022-10-11 08:17 UTC, SeongJoon-K requested changes

2022-10-11 08:17 UTC, SeongJoon-K commented on teamA/leeChanWoo/app.js
> +const dotenv = require('dotenv').config();
해당 부분 아래와 같이 수정해 주시고, 최상단으로 올려주세요 !
```suggestion
require('dotenv').config();
```

2022-10-12 05:19 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-10-12 05:19 UTC, merged