[정재욱-teamB] Assignment 3: Express API - CRUD
wecode-bootcamp-korea/38-backend-westagram pull request #12
Opened 2022-10-06 07:48 UTC by dnrdls7

## 수정 사항 간략한 한줄 요약
- CRUD 기능 구현
		 
## 수정 사항들 자세한 내용
- 게시글 등록 : [POST] /posts/add 로 요청이 올 때, posts table에 들어갈 title, content, user_id의 정보를 받아 table에 data 추가함
- 전체 게시글 조회 : [GET] /posts/list/all 로 요청이 올 때, posts table data를 형식에 맞게 출력함.
- 유저의 게시글 조회 : [POST] /posts/list/userid 특정 유저의 id의 정보를 받아 해당 유저의 게시글을 posts table에서 data를 가져오고, users table에서 유저의 name을 가져옴. 형식에 맞게 users table data에 객체형식으로 만들고 posts table data는 배열 형식으로 users data의 property의 value로 할당함.
- 게시글 수정 : [POST] /posts/update 로 user_id, post_id, content를 입력받아, 게시물의 content를 수정함.
- 게시글 삭제 : [DELETE] /posts/delete 로 post_id를 입력받아 해당 게시물을 posts table에서 id로 찾아 삭제함.
- 좋아요 기능 : [POST] /posts/like 로 좋아요를 누른 user_id와 좋아요 당한 게시물 post_id를 정보로 받아, likes middle table에 정보를 추가하는 기능.

## 기타 질문 및 특이 사항
http 요청 하나당 query문을 1개 이상 사용시 (promise all 제외) 오류가 나는 이유를 정확하게 모르겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-07 06:49 UTC, dnrdls7 commented
assignment 1~2 과정에서 발생한 수정 요청 건들을 반영하고, merge 됨에 따라 main branch를 pull 하고,
1~2 과제에서 수정했던 사항들(conflict)을 수정하였습니다.

2022-10-08 04:42 UTC, SeongJoon-K requested changes

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    `,
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.

```suggestion
  await mysqlDataSource.query(`
    SELECT
      users.id as userId,
      users.profile_image as userProfileImage,
      posts.id as postingId,
      posts.profile_url as postingImageUrl,
      posts.content as postingContent
    FROM users 
    INNER JOIN posts ON users.id = posts.user_id;`,
```

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +      `
- 해당 부분도 위코드 SQL 포맷팅을 지켜서 문법을 사용해 주세요

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +app.get('/posts/list/userid', async (req, res) => {
해당 api는 path parameter 에서 userId로 받은 특정 유저가 작성한 글 목록을 불러오는 기능을 하는 것 같네요.

그렇다면 엔드포인트를 지금과 같이 /post/list/userId 보다 /users/:userId/posts 로 작성하는 것이 조금 더 자명한 엔드포인트를 만들 수 있을 것 같습니다.


```
# Case 1
http -v GET localhost:3000/posts/1   # 엔드포인트만 보고 유추하기로는 1번 post(게시글) 의 정보를 받아올 것 같은 느낌입니다

# Case 2
http -v GET localhost:3000/users/1/posts   # 1번 유저의 게시글들(posts : 복수)을 불러오는 엔드포인트처럼 보이지 않나요?
```

```suggestion
app.get('/users/:userId/posts', async (req, res) => {
```

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +
- 해당 부분도 SQL 포맷팅을 지켜서 수정해 주세요 ~!

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    )
- SQL 포맷팅을 지켜서 수정해주세요 !

```suggestion
    await mysqlDataSource.query(`
      UPDATE posts
      SET content="${content}"
      WHERE user_id=${user_id} AND id=${post_id};
      `),
    mysqlDataSource.query(`
      SELECT
        users.id as userId,
        users.name as userName,
        posts.id as postingId,
        posts.title as postingTitle,
        posts.content as postingContent
      FROM users 
      INNER JOIN posts ON users.id = posts.user_id 
      AND users.id=${user_id} AND posts.id=${post_id};`
    )
```

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    `,
- 해당 부분도 SQL 포맷팅을 지켜서 수정해 주세요 ~!

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    `,
해당 부분도 SQL 포맷팅을 지켜서 수정해 주세요 ~!

2022-10-08 04:42 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +app.post('/posts/add', async (req, res) => {
- 현재 endpoint에서 /add 는 POST 요청 자체가 등록을 요청한다는 의미도 포함되어 있기에 restful 하지 않다고 볼 수 있습니다!
- 해당 endpoint를 GET의 /posts, POST의 /posts 처럼 엔드포인트는 같으나, 요청 메소드가 다르기 때문에 자명한 endpoint를 만들 수 있을 거 같습니다 ~

```suggestion
app.post('/posts', async (req, res) => {
```

이렇듯 자명한 엔드포인트를 작성하는 것에 대해 REST하게 엔드포인트를 작성한다고 합니다.
해당 내용은 이후에 있을 RESTful API 세션에서 다뤄질 예정이니 참고해주세요 :)

2022-10-09 01:23 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +    `,
수정하겠습니다.

2022-10-09 01:24 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +      `
수정하겠습니다.

2022-10-09 01:25 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +
수정하겠습니다.

2022-10-09 01:25 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +    )
수정하겠습니다.

2022-10-09 01:25 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +    `,
수정하겠습니다.

2022-10-09 01:26 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +    `,
수정하겠습니다.

2022-10-09 01:27 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +app.post('/posts/add', async (req, res) => {
수정하겠습니다.

2022-10-09 01:32 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +app.get('/posts/list/userid', async (req, res) => {
path parameter를 사용한 방법은 아니지만, 설명해주신 엔드포인트가 더 직관적으로 특정 유저의 게시물임을 의미하는 것 같습니다.
path parameter 방법이 훨씬 좋은 듯 보여서 추후 layered pattern에서는 스터디 후에 적용해보겠습니다.

2022-10-09 01:43 UTC, dnrdls7 commented
엔드포인트 url, query 포맷팅 수정 지시 사항 적용하였습니다.

2022-10-09 08:24 UTC, SeongJoon-K requested changes

2022-10-09 08:24 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    `,
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하시면 좋을거 같습니다.

```suggestion
  await mysqlDataSource.query(`
      SELECT
          users.id as userId,
          users.profile_image as userProfileImage,
          posts.id as postingId,
          posts.profile_url as postingImageUrl,
          posts.content as postingContent
        FROM users
        INNER JOIN posts ON users.id = posts.user_id;`,
```

2022-10-09 08:24 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    )
- 해당 부분도 쿼리문을 수정해주세요 !

2022-10-09 08:24 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +  );
- 해당 부분도 쿼리문 포맷팅을 지켜주세요 ~!

2022-10-09 08:24 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    )
- 이 부분도 마찬가지로 포맷팅을 고쳐주세요!

2022-10-09 08:24 UTC, SeongJoon-K commented on teamB/jungJaeUk/app.js
> +    `,
- 쿼리문 포맷팅을 지켜서 수정해주세요 ~!

2022-10-09 09:39 UTC, dnrdls7 commented
query문 백틱 위치 변경 완료했습니다.

2022-10-11 00:54 UTC, kyeongraekim requested changes

2022-10-11 00:54 UTC, kyeongraekim commented on teamB/jungJaeUk/app.js
> +//[GET] posts list all
코드 독해로 의미 파악이 가능한 간단한 부분에 대해서는 굳이 상용화될 코드로 푸시되는 깃헙상의 코드에서 지워주셔도 될 것 같아 보입니다. 전반적으로 app.httpmethod 앞에서 선언해주신 다양한 주석 설명문을 제거해주세요~

2022-10-11 00:56 UTC, kyeongraekim requested changes

2022-10-11 00:56 UTC, kyeongraekim commented on teamB/jungJaeUk/app.js
> +});
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```
    
- JavaScript에서 비동기 처리할 수 있는 callback과 async/await 방식의 차이를 알고 싶다면, 아래 영상(드림코딩 Youtbue)을 참고해주세요.
[https://www.youtube.com/watch?v=aoQSOZfz3vQ](https://www.youtube.com/watch?v=aoQSOZfz3vQ)

2022-10-11 03:33 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +//[GET] posts list all
주석 지우겠습니다.

2022-10-11 03:36 UTC, dnrdls7 commented on teamB/jungJaeUk/app.js
> +});
수정하겠습니다.

2022-10-11 05:38 UTC, kyeongraekim commented on teamB/jungJaeUk/app.js
> +});
해당 방식을 callback으로 모두 변경해주셨는데 기능적으로는 잘 돌아갈 것 같습니다. 하지만 callback은 async-await 보다 기본적으로 속도, 가독성, 비동기적 동작에서 더 불리한 부분이 있음으로 해당부분을, ES6 기반의 보다 최신 문법을 반영하여 async-await 방식으로 일괄 수정해주세요.

2022-10-11 05:48 UTC, dnrdls7 commented
callbqck -> async-await 수정

2022-10-11 06:00 UTC, kyeongraekim requested changes

2022-10-11 06:00 UTC, kyeongraekim commented on teamB/jungJaeUk/etc/userDaoPosts.js
> +  });
- 현재 모든 Dao에서 해당 initialize 코드의 내용이 동일하게 반복 적용되는 것을 느끼실 수 있으실 겁니다. 코드 작성시 모듈화라는 작업을 통해서 재반복되는 코드를 언제어디서든지 재사용할 수 있게 처리하는 모습이 필요시 됩니다. 
-  현재는 불필요하게 매번 새로운 서버를 각 Dao에서 연결하여서 사용하는 모습을 띄고 있다고 보시면 됩니다.
- 해당 내용을 별도의 파일로 작성하여서 서버 작동시 하나로 발동된 Datasource 객체를 다른 여러 Dao.js 파일들이 사용할 수 있게 유도할 수 있을지 그 방법론을 고민해보세요!~

2022-10-11 06:00 UTC, kyeongraekim commented on teamB/jungJaeUk/etc/userDaoPosts.js
> +  });
- 해당 내용을 적용하기 위해서는 app.js에서 app과 서버연결등 앱동작의 모든것을 한 파일에서 처리하던 interface 방식에서, app.js 와 server.js 나누어 앱의 기능, 서버 연결을 담당하는 파일을 나누어서 접근해야 된다는 점을 힌트로 먼저 알려드립니다.

2022-10-11 06:05 UTC, kyeongraekim commented on teamB/jungJaeUk/etc/userDaoPosts.js
> +  });
- 다시 보니 Mission 3의 내용에 Mission 4의 내용이 흘러들어간 것 보면 아마 브랜치를 main에서 새롭게 파신게 아니고 서로의 브랜치를 연결되게 파주신 것 같네요~ app.js 단일 파일에서 작동하는 해당 내용을 다시 푸시해주시면 감사하겠습니다~

2022-10-11 06:50 UTC, dnrdls7 commented on teamB/jungJaeUk/etc/userDaoPosts.js
> +  });
main 에서 새로 만든 branch에서 작업했습니다.
layered pattern 수정 지시 사항을 진행하면서, 폴더를 하나 만들어서 기존에 수정 지시 받았던 코드들을 넣어놨는데,
이 폴더가 같이 푸쉬된 것 같습니다.

2022-10-11 08:26 UTC, kyeongraekim approved these changes
LGTM!~ Layered Pattern 작성해주신 내용 이어서 푸시해주세요! dao 부분 initialize의 모듈화도 꼭 도전하여서 푸시해주세요~

2022-10-11 08:26 UTC, merged