[이현태-teamA] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/38-backend-westagram pull request #13
Opened 2022-10-06 08:14 UTC by iflov

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
초기설정 완료하였습니다~
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-node.js 프레임워크 Express 설치 
-.env > process.env에 넣어주는 dotenv 설치 
- package.json 만들기 
- sop완화를 위한 cors설치 
- logging을 위한 morgan설치
- db와 object연결을 위한 typeorm 설치
등

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-06 08:32 UTC, kyeongraekim requested changes

2022-10-06 08:32 UTC, kyeongraekim commented on teamA/leehyeontae/.env.sample
> +PORT=// port (http port)
자바스크립트의 주석문처럼 보이는 // 표시가 불필요하게 들어가 있는 것 같아 보입니다. 해당 내용은 삭제해주시고 env.sample 파일은 말그대로 어떠한 내용이 들어갈 것인지에 대한 샘플링의 내용이 담기는 파일이오니 너무 디테일하게 작성할 필요는 없습니다.

2022-10-06 08:32 UTC, kyeongraekim commented on teamA/leehyeontae/.env.sample
> +
- 이곳에서도 다양한 자바스크립트 주석문처럼 보이는 것들이 보이는데, 사용하시는 파일 확장자에 따라서 주석을 나타내는 syntax 문법이 다양하게 달라집니다. 따라서 //표시가 .env 파일의 주석문 처리 방법이 맞는지 다시 한 번 확인해 볼 필요가 있어 보입니다. 참고로 .env 파일은 주석처리시 #을 사용합니다. 
- 다만 한가지 고려사항은, 이미 key-value 형태에서 어떠한 목적을 지닌 환경변수 내역인지 분명하게 의도와 의미 파악이 되는 만큼 불필요한 주석을 굳이 넣어주실 필요는 없어 보입니다.

2022-10-07 00:41 UTC, sangwoong03 commented on teamA/leehyeontae/.env.sample
> +PORT=// port (http port)
해당 부분 수정 안된 것 같은데 확인해주세요.

2022-10-07 00:44 UTC, closed without merging