[천송인-teamB] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/38-backend-westagram pull request #18
Opened 2022-10-06 08:44 UTC by csongin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- name, email, profile_image, password 입력 가능
- 성공시 201 OK 반환
- ![users db save](https://user-images.githubusercontent.com/100663230/194267116-31933460-6e6f-470f-8b42-61beb8b8ae66.png)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- INSERT INTO users 부분 변수에 담아서 활용도 가능한가요!?(해보면 알겠지만..될 것 같습니다)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-06 09:24 UTC, SeongJoon-K requested changes

2022-10-06 09:24 UTC, SeongJoon-K commented on teamB/cheonsongin/app.js
> +  // console.log(req);
개발시 사용한 불필요한 console.log 는 제거해주세요 ~!
```suggestion
```

2022-10-06 11:20 UTC, sangwoong03 commented on teamB/cheonsongin/db/schema.sql
> +/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-10-06 11:20 UTC, sangwoong03 commented on teamB/cheonsongin/package.json
>      "morgan": "^1.10.0",
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.
- mysql & mysql2 드라이버 패키지는 서로 동일한 기능을 하는 패키지 입니다. 따라서 둘 중 하나를 선택하여 설치를 진행해주세요.

송인님 확인 후 기존 패키지의 `dependencies`인지 혹은  `devDependencies`인지 위치도 수정해보세요!

2022-10-09 08:25 UTC, SeongJoon-K requested changes
송인님 ! 상웅님이 위에서 schema.sql 말씀해 주신거에 대해서 한 번 더 수정 요청 드립니다 !! 😃

2022-10-11 05:09 UTC, SeongJoon-K approved these changes

2022-10-11 05:09 UTC, merged