[이찬우-teamA] Assignment 3: Express API - CRUD
wecode-bootcamp-korea/38-backend-westagram pull request #24
Opened 2022-10-06 14:13 UTC by c0zyb1ue

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 게시글 등록 API 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +// health cheak
불필요한 주석은 삭제해주세요!

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +// sign-up
불필요한 주석은 삭제해주세요!

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +// posts에 게시글 등록
불필요한 주석은 삭제해주세요!

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +// 전체 게시글 조회하기
불필요한 주석은 삭제해주세요!

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +	);
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
 ```suggestion
	await myDataSource.query(
		`INSERT INTO users(
			name,
			email,
			profile_image,
			password
		) VALUES (?, ?, ?, ?);`,
		[ name, email, profile_image, password ]
	); 
```

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +     res.status(201).json({ message : "postCreated" });
마찬가지로 코드 포맷팅 수정해주세요!

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +
불필요한 여백 삭제해주세요!

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/package.json
> +  }
이전 PR에서와도 마찬가지로 리마인드 드립니다~

dependencies와 devDependencies의 차이점을 확인해서 수정해주세요~

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +        FROM posts
Alias 설정하는 방식을 통일해주세요.
    
    ```sql
    -- Alias 나쁜 예
    
    SELECT 
      u.id AS id
    FROM users u
    INNER JOIN posts p ON p.user_id = u.id
    
    -- Alias 좋은 예 1
    SELECT 
      u.id AS id
    FROM users AS u
    INNER JOIN posts AS p ON p.user_id = u.id
    
    -- Alias 좋은 예 2
    SELECT 
      u.id id
    FROM users u
    INNER JOIN posts p ON p.user_id = u.id
    ```

2022-10-07 05:49 UTC, sangwoong03 commented on teamA/leeChanWoo/app.js
> +		,(err, rows) => {
해당 코드 실행해보셨나요?

2022-10-12 04:59 UTC, SeongJoon-K requested changes
schema.sql 파일이 github 상에서 관리되고 있습니다 ! 해당부분 수정해주세요 !

2022-10-12 08:52 UTC, sangwoong03 commented
찬우님! 해당 브랜치도 파일 구조 확인해보고 다시 푸시해주세요!
`.gitignore` `env.sample` 파일이 같이 안올라왔네요~!

2022-10-13 01:53 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-10-13 01:53 UTC, merged