[김성훈-teamB] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/38-backend-westagram pull request #29
Opened 2022-10-07 02:15 UTC by Hey-Hello-World

##  작업 내역
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 유저 회원 가입하기 기능 구현 
		 
## 작업 내역에 대한 내용
- POST 메소드를 이용하여 name, email, profile_image, password 정보 받아솨 database users table에  유저를 추가함.
- 성공 시 201 Created  및 "message": "userCreated" 반환
- 실패 시 'catch 메소드'를 통한 에러 반환

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-08 04:51 UTC, SeongJoon-K requested changes
schema.sql 의 경우 프로젝트 진행시 git 상에서 관리하기 어려운 경우가 있어 .gitignore을 통해서 관리해야합니다. 해당 파일을 .gitignore에 포함시키고 github에 관리되지 않게 해 주세요~!

2022-10-08 04:51 UTC, SeongJoon-K commented on teamB/kimSungHoon/app.js
> +const dotenv = require('dotenv').config();
- dotenv 의 경우 const 선언을 하지 않고 바로 호출과 적용이 가능합니다. 아래와 같이 수정해주세요 ~!
```suggestion
require('dotenv').config();
```

2022-10-09 08:11 UTC, SeongJoon-K requested changes
성훈님 ! schema.sql은 개별 로컬 환경에 따라 그 세부 내용이 다를 수 있으니 다른 개발자들과 함께 관리하는 순간 많은 에러를 낼 가능성이 있습니다. 해당 내용은 .gitignore에 추가하여서 GitHub에 올라오지 않도록 설정해 주세요.

2022-10-11 01:01 UTC, kyeongraekim approved these changes
LGTM!~

2022-10-11 01:01 UTC, merged