[천송인-teamB] Assignment 1:  Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/38-backend-westagram pull request #3
Opened 2022-10-05 10:09 UTC by csongin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Express 초기 환경 설정
- TypeORM / dbConnection 설정
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- Express 설치 / 적용
- nodemon 설치 / 적용
- cors 설치 / 적용
- dotenv 설치 / 환경 변수 적용
- morgan 설치 / 적용
- TypeORM 설치 및 적용
- dbConnection 정상 작동 확인

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 전체적인 구조를 이해하면서 설치를 해야하는데, 많이 부족한 것 같습니다.
- 설치 이후에도 복습 예정입니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다. (개인 과제)

2022-10-05 10:14 UTC, kyeongraekim requested changes

2022-10-05 10:14 UTC, kyeongraekim commented on teamB/cheonsongin/app.js
> +dotenv.config();
7번 라인의 코드와 중복되어 보입니다. 해당 내용 확인 후 수정해주세요!~

2022-10-05 10:14 UTC, kyeongraekim commented on teamB/cheonsongin/app.js
> +  res.json({ message : 'dev' });
ping-pong 에 해당되는 health check 컨벤션에 맞게 dev가 아닌 pong으로 수정해주세요!~

2022-10-06 05:15 UTC, kyeongraekim requested changes

2022-10-06 05:15 UTC, kyeongraekim commented on teamB/cheonsongin/app.js
> +const myDataSource = new DataSource({
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- DataSource.initialize() 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.
- 추후 에러 핸들링을 담을 때의 가독성 및 확장성 보장을 위해 ".then"을 (typeorm datasource 공식문서에서 제안하는 것 처럼) 한칸 아래로 띄는 것을 권장드립니다.
- 참고 링크: [https://typeorm.biunav.com/en/data-source.html#what-is-datasource](https://typeorm.biunav.com/en/data-source.html#what-is-datasource)

2022-10-06 07:56 UTC, lordmyshepherd approved these changes
LGTM 👍🏻

2022-10-06 07:56 UTC, merged