[박은송-teamB] Assignment 3: Express API - CRUD API 만들기
wecode-bootcamp-korea/38-backend-westagram pull request #30
Opened 2022-10-07 02:51 UTC by Eunsong-Park

## 수정 사항 간략한 한줄 요약
- 수정 사항 반영하여 전체 기능 추가 완료 후 PR
		 
## 수정 사항들 자세한 내용
- 초기 환경 세팅
- 유저 회원가입 기능 구현
- 게시글 등록 기능 구현
- 전체 게시글 조회 기능 구현
- 유저의 게시글 조회 기능 구현
- 게시글 수정 기능 구현
- 게시글 삭제 기능 구현
- 좋아요 누르기 기능 구현
- 이전 PR 에서의 수정사항 모두 반영

## 기타 질문 및 특이 사항
- TypeORM 에서 database.manager.query 와 database.query의 차이가 무엇인지 궁금합니다.
- js 파일 내 sql문 들여쓰기 방식이 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-09 08:38 UTC, SeongJoon-K requested changes

2022-10-09 08:38 UTC, SeongJoon-K commented on teamB/eunsong/app.js
> +
- 은송님 ! dotenv 모듈의 경우 최상단에
require('dotenv').config() 로 작성해 주세요 !

2022-10-09 08:38 UTC, SeongJoon-K commented on teamB/eunsong/app.js
> +        WHERE id=${userId}`
- 해당 부분 쿼리문의 indentation을 맞춰주세요 !
```suggestion
    `SELECT
            u.id AS userId,
            u.profile_image AS userProfileImage
      FROM users u
      WHERE id=${userId}`
```

2022-10-09 08:38 UTC, SeongJoon-K commented on teamB/eunsong/app.js
> +  );
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
    
    ```jsx
    // Example
    await database.query(`
      UPDATE posts
      SET title = ?,
        description = ?
      WHERE id = ?`,
      [title, description, postId]
    );
    ```

2022-10-09 08:42 UTC, SeongJoon-K commented
질문해 주신 js파일에 있어서 SQL포맷팅 예시를 아래 첨부하였습니다 ! 

- INSERT 포맷팅
```
// Example
await database.query(`
      INSERT INTO users (
          name,
          email,
          profile_image,
          password
      ) VALUES (?, ?, ?, ?)`,
      [ name, email, profile_image, password ]
);

```

- SELECT, JOIN 포맷팅

```
// Example
await database.query(`
		SELECT 
			users.id,
			users.name,
			posts.id,
			posts.title,
			posts.content
		FROM posts
		JOIN users ON users.id = posts.user_id
		WHERE posts.id = ..`
);
```

- UPDATE 포맷팅
```
// Example
await database.query(`
  UPDATE posts
  SET title = ?,
    description = ?
  WHERE id = ?`,
  [title, description, postId]
);
```

2022-10-10 03:49 UTC, Eunsong-Park commented on teamB/eunsong/app.js
> +
네 해당 5-6 번째 줄 지우고 app.js 파일 최상단 1번째 줄에
require('dotenv').config() 로 작성하겠습니다.

2022-10-10 03:51 UTC, Eunsong-Park commented on teamB/eunsong/app.js
> +        WHERE id=${userId}`
폴더 내 모든 sql 쿼리문을 위코드 컨벤션에 맞게 수정하겠습니다.

2022-10-10 03:51 UTC, Eunsong-Park commented on teamB/eunsong/app.js
> +  );
폴더 내 모든 sql 쿼리문을 위코드 컨벤션에 맞게 수정하겠습니다.

2022-10-10 05:53 UTC, merged