[김성훈-teamB] Assignment 3: Express API - CRUD
wecode-bootcamp-korea/38-backend-westagram pull request #34
Opened 2022-10-07 11:42 UTC by Hey-Hello-World

##  작업 내역 
- 게시글 등록 API 구현
- 데이터가 잘 db에 저장되었는지 여부를 테이블 스크린샷

![image](https://user-images.githubusercontent.com/107197044/194544778-1e16428c-1f90-4f5b-869d-d5682707ed0a.png)
	 
## 작업 내역 세부사항
- POST 메소드를 이용하여 title, content, user_id 등록 
- 성공시 201 Created 반환
- 실패 시 에러 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-10 05:56 UTC, SeongJoon-K requested changes
성훈님 ! 
schema.sql 파일이 아직 포함되어 있습니다 ! 해당 부분 확인후 수정 부탁드려요!

2022-10-11 01:03 UTC, kyeongraekim requested changes

2022-10-11 01:03 UTC, kyeongraekim commented on teamB/kimSungHoon/.env.sample
> +DATABASE_URL="mysql://root:kambo@127.0.0.1:3306/database"
kambo라는 워딩이 혹시 직접 사용하는 비밀번호를 의미하는 것이면 보안상의 큰 위험을 야기함으로, 제 3자와 공유하는 깃헙상에서는 꼭 삭제를 해주셔야 합니다. 해당 내용을 제거해주시고 푸시해주세요!~

2022-10-11 05:47 UTC, kyeongraekim commented
현재 mission 1 부터 머지가되지 않아 적재되어 있는 형태로 보여지네요. 깃 플로우에 대한 전략고민도 개발자라면 필히 함께 진행해주셔야 합니다. Initial-setting 부터 차근차근 머지되어서 현재 브랜치까지 빌드업되어 머지될 수 있도록 앞선 과제들부터 하나하나 해결해주세요.

2022-10-11 06:30 UTC, SeongJoon-K approved these changes

2022-10-11 06:30 UTC, SeongJoon-K commented on teamB/kimSungHoon/.env.sample
> +
- `kambo`라는 코드가 어떤 것을 넣어야 하는지 보는 사람의 입장에서 헷갈릴 수 있습니다. `yourpw`와 수정해 주세요

2022-10-11 08:33 UTC, kyeongraekim requested changes

2022-10-11 08:33 UTC, kyeongraekim commented on teamB/kimSungHoon/.env.sample
> +TYPEORM_PORT = 3306
SAMPLE_VALUE로 작성해주신 부분은 수정 전이 더 적절해보이네요~ 환경변수로서 치환되어 들어가는 값이 상수데이터임으로 네이밍 컨벤션을 따라서 camel case 보다 대문자표현 + 언더바인 SNAKE_CASE 표현이 제일 적절하다는 사실을 알려드립니다~

2022-10-11 08:33 UTC, kyeongraekim commented on teamB/kimSungHoon/app.js
> +})
- 작성하신 코드에서 DataSource.query()가 비동기적으로 실행되는 함수입니다.
- 비동기 처리를 하는 방법은 크게 callback, promise, async/await를 사용하는 방법이 있는데, 작성하신 코드에서는 이를 혼합해서 사용하고 있습니다. 아래 예제를 참고해서 async-await의 방법으로  리펙토링해주세요.
    
    ```jsx
    // callback 방식의 비동기처리
    app.get("/posts", (req, res) => {
        myDataSource.query(`SELECT * FROM users`,
          // 비동기 처리 이후에 실행되는 callback
          (err, data) => {res.status(200).json({ data: data })}
        );
    });
    
    // async와 await 방식의 비동기처리
    app.get("/posts", async(req, res) => {
      const users = await myDataSource.query(`SELECT * FROM users`);
      
      res.status(200).json({ data : users})
    });
    
    ```

2022-10-13 02:07 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-10-13 02:07 UTC, merged