[정해만1-teamA] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/38-backend-westagram pull request #43
Opened 2022-10-09 05:39 UTC by haemong

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- express 초기 환경 설정
  라이브러리 세팅(express, cors, morgan, dotenv, typeorm)
- TypeORM/ dbConnection 설정

## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- gitignore에 masOS, Linux, node, doting 내용 추가

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-11 01:43 UTC, SeongJoon-K requested changes
migrations 디렉토리에 있는 sql 파일의 내용을 채워주세요 해만님 !

2022-10-11 08:21 UTC, SeongJoon-K requested changes
.env.sample의 파일명 수정 부탁드립니다 !

2022-10-11 13:23 UTC, sangwoong03 commented on teamA/jeongHaeMan1/app.js
> +app.use(morgan(''));
morgan 미들웨어의 format을 지정하지 않는다면, default format이 적용됩니다.
서버를 실행하여 터미널 상 로그를 확인해보세요!  morgan 미들웨어 관련된 로그가 한 줄 나올 것입니다.

morgan format에 대해 찾아보고 큰따옴표를 제거하거나, 다른 format을 지정해주세요~!

아래는 예시입니다!

```suggestion
app.use(morgan('dev'));
```

2022-10-12 01:06 UTC, SeongJoon-K approved these changes

2022-10-12 01:06 UTC, merged