[정재욱-teamB] Assignment 2: Express API - 유저 회원가입 하기
wecode-bootcamp-korea/38-backend-westagram pull request #5
Opened 2022-10-05 12:35 UTC by dnrdls7

## 수정 사항 간략한 한줄 요약
- 유저 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
- name, email, profile_image, password 정보를 포함한 POST 요청이 들어오면
- database users table에 user를 추가함.
- 실패시 에러반환
- 성공시 201 Created / "message": "userCreated" 반환

## 기타 질문 및 특이 사항
- 포함해야하는 정보를 필수사항, 선택사항으로 분류하고 싶습니다.
- profile_image 같은 경우 선택사항으로 받고 싶은데 비구조화 할당에서 방법을 찾아보고 있습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-06 05:24 UTC, kyeongraekim requested changes, later dismissed
db 폴더 내부에서 관리하는 migrations 파일이 보이지 않네요. 비록 개인과제이지만 만일 팀과 함께 협업하는 과제라고 가정한다면 함께 migration 파일을 공유하여 로컬 내 디비를 동일하게 구조화하는 것이 중요할 것 입니다. dbmate 작업시 만들어지는 migration 파일들도 함께 올라올 수 있도록 재푸시해주세요~

2022-10-06 07:25 UTC, dnrdls7 commented
> db 폴더 내부에서 관리하는 migrations 파일이 보이지 않네요. 비록 개인과제이지만 만일 팀과 함께 협업하는 과제라고 가정한다면 함께 migration 파일을 공유하여 로컬 내 디비를 동일하게 구조화하는 것이 중요할 것 입니다. dbmate 작업시 만들어지는 migration 파일들도 함께 올라올 수 있도록 재푸시해주세요~

2022-10-06 12:27 UTC, dnrdls7 commented
초기환경 세팅 머지 된 main pull 진행하였습니다.
conflict 해결
schema.sql 삭제 요청 및 gitignore에 추가하였습니다.

2022-10-07 05:21 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-07 05:26 UTC, sangwoong03 approved these changes
LGTM 👍

2022-10-07 05:30 UTC, merged