[teamB-심채원]feature/simchaewon-layered-initial
wecode-bootcamp-korea/38-backend-westagram pull request #53
Opened 2022-10-10 10:04 UTC by tlacodnjs667

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
-초기 세팅 / 회원가입 / 포스팅 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 회원가입 시 유저 이름, 이메일, 비밀번호, 프로필 이미지 데이터 베이스에 저장
- 포스팅 시 유저의 이름을 입력하면 users table에서 유저 id 값을 찾아 posts table의 fk 값으로 저장

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 현재 발생하는 문제 post 등록시 완료 메세지가 뜨지 않습니다. 어떤 이유 때문인지 모르겠습니다.
- 전체 게시글부터 CRUD 브랜치에 올리겠습니다! 죄송합니다!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [✓ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [✓ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ✓] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ✓] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-11 02:17 UTC, SeongJoon-K commented on teamB/simchaewon/app.js
> +require("dotenv").config();
해당 부분은 최상단으로 올려서 작성해주세요 !
```suggestion
require("dotenv").config();
```

2022-10-11 02:17 UTC, SeongJoon-K commented on teamB/simchaewon/models/postDao.js
> +            );
- 해당 쿼리문을 백틱으로 수정해서 indentation을 맞춰서 작성해 주세요 !

2022-10-11 02:17 UTC, SeongJoon-K commented on teamB/simchaewon/models/postDao.js
> +
- 해당 쿼리문도 백틱으로 indentation을 맞춰서 수정해주세요 !

2022-10-11 02:17 UTC, SeongJoon-K commented on teamB/simchaewon/models/postDao.js
> +// Zz
개발시 작성한 주석 및 콘솔을 PR 요청시 제거해 주세요 !

2022-10-11 02:17 UTC, SeongJoon-K commented on teamB/simchaewon/models/userDao.js
> +				);
- 해당부분 indentation을 맞춰주세요 !

2022-10-11 02:17 UTC, SeongJoon-K commented on teamB/simchaewon/models/userDao.js
> +		);
- 해당 부분도 indentation을 맞춰서 수정해주세요 !

2022-10-12 02:13 UTC, SeongJoon-K requested changes

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/db/migrations/20221010055814_create_posts_table.sql
> +);
indentation을 맞춰서 SQL문을 수정해주세요 !
```suggestion
CREATE TABLE posts (
        id INT NOT NULL AUTO_INCREMENT,
	title VARCHAR(200) NOT NULL,
        content VARCHAR(1000) NOT NULL,
        user_id INT NOT NULL,
        post_image VARCHAR(200) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
        FOREIGN KEY (user_id) REFERENCES users(id)
);
```

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/models/likeDao.js
> +        );
- SQL 쿼리문 포맷팅을 맞춰서 수정해주세요 !
```suggestion
        return await westa_DB.query(`
        INSERT INTO likes (
            user_id, 
            post_id
        ) VALUES (?, ?);`,
        [userId, postId]
        );
```

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/models/postDao.js
> +    );
마찬가지로 SQL 쿼리문 포맷팅에 맞춰 수정해주세요 !
```suggestion
    const id = await westa_DB.query(`
        SELECT id 
          FROM users 
          WHERE users.name=? ;`,
      [userName]
    );
```

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/models/postDao.js
> +      [title, content, id[0].id, postImage]
- 위와 마찬가지로 쿼리문 indentation을 맞춰주세요 !
```suggestion
    return await westa_DB.query(`
        INSERT INTO posts (
          title,
          content, 
          user_id, 
          post_image
      ) VALUES (?,?,?,?)`,
      [title, content, id[0].id, postImage]
```

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/models/postDao.js
> +    );
위와 마찬가지로 쿼리문을 수정해주세요 !

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/models/userDao.js
> +    );
마찬가지로 쿼리문을 수정해주세요 !

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/models/userDao.js
> +    );
마찬가지로 쿼리문을 수정해주세요 !

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/package.json
> +    "mysql": "^2.18.1",
mysql & mysql2 드라이버 패키지는 서로 동일한 기능을 하는 패키지 입니다. 따라서 둘 중 하나를 선택하여 설치를 진행해주세요.

이미 설치된 패키지나 모듈은 코드만 지우는 것이 아닌, 패키지 매니저 명령어를 통해 삭제해야합니다.

`npm uninstall PACKAGE_NAME`

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/routes/postRouter.js
> +router.delete("/delete", postController.deletePost);
코드 가독성을 위해 해당 부분은 한 줄을 띄어서 작성해 주세요!
```suggestion
const router=express.Router();

router.post("/upload", postController.upload);
router.get("/readall", postController.readall);
router.patch("/update", postController.update);
router.delete("/delete", postController.deletePost);
```

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/routes/userRouter.js
> +//useerRouter의 router를 보내는 겨
개발 시 작성한 주석은 제거해주세요 !
```suggestion
```

2022-10-12 02:13 UTC, SeongJoon-K commented on teamB/simchaewon/services/userService.js
> +  // password validation using REGEX
개발 시 작성한 주석은 제거해주세요 !
```suggestion
```

2022-10-13 02:52 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-10-13 02:52 UTC, merged