[천송인-teamB] Assignment 1: Layered Pattern
wecode-bootcamp-korea/38-backend-westagram pull request #54
Opened 2022-10-10 14:24 UTC by csongin

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- app.js에 모두 모여 있던 소스 코드를 각 기능별로 routes, controllers, services, models 모듈화하여 분리
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 중복되는 코드가 많은데, 어떻게 효율적으로 줄일 수 있는지가 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-11 02:21 UTC, SeongJoon-K requested changes

2022-10-11 02:21 UTC, SeongJoon-K commented on teamB/cheonsongin/app.js
>  dotenv.config();
- dotenv 호출시 아래와 같이 수정해주시고, 최상단에 작성해주세요 ~!
```suggestion
require('dotenv').dotenv.config();
```

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/routes/postRouter.js
> +router.delete('/delete', postController.postDelete);
위코드에서는 RESTful API 기반의 API를 작성합니다.

추후 세션을 통해 배울 내용이지만, RESTful API에서 엔드포인트를 구축할 때엔 동사가 아닌 명사로 작성합니다.

```suggestion
router.post('/posts', postController.upload);
router.get('/posts', postController.viewAllPosts);
router.get('/posts/:userid', postController.viewUserId);
router.put('/posts', postController.postUpdate);
router.delete('/posts', postController.postDelete);
```

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/app.js
> +require('dotenv').dotenv.config();
해당 코드로 서버를 실행했을 시 오류가 발생할 것입니다.
수정해주세요!
```suggestion
require('dotenv').config();
```

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/routes/likeRouter.js
> +const router = express.Router();
mport 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 이런 컨벤션 준수들이 모여서 좀 더 가독성 좋은 코드가 됩니다

```suggestion
const express = require('express');
const router = express.Router();

const likeController = require('../controllers/likeController');

```

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/routes/postRouter.js
> +const router = express.Router();
import 순서 수정해주세요!

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/routes/userRouter.js
> +const router = express.Router();
import 모듈 수정해주세요!

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/services/userService.js
> +  );
자바스크립트에서 문자열을 변수에 담을 때 변수는 대문자로 작성하는 컨벤션이 있습니다. 참고해주세요~!
```suggestion
  const PASSWORD_REGEX = new RegExp(
    '^(?=.*[A-Za-z])(?=.*[0-9])(?=.*[!@#$%^&*])(?=.{8,20})'
  );
```

2022-10-11 22:53 UTC, sangwoong03 commented on teamB/cheonsongin/models/likeDao.js
> +  });
해당 코드는 반복이 되고 있습니다.

지금은 3개의 파일만 관리하면 되므로 유지보수 측면에서 어려움이 없지만 100개가 된다면 굉장히 비효율적이고 불필요한 코드일 것입니다.

models 파일 혹은 utils 파일 내에 `dataSource.js` 혹은 `appDataSource.js` 파일 생성 후 해당 코드를 옮겨적어주세요.
이후 DataSource라는 새로운 객체를 담은 appDataSource 객체를 내보내주면 됩니다!

```suggestion
// 모듈 분리
const { DataSource } = require('typeorm');

const appDataSource = new DataSource({
  type: process.env.TYPEORM_CONNECTION,
  host: process.env.TYPEORM_HOST,
  port: process.env.TYPEORM_PORT,
  username: process.env.TYPEORM_USERNAME,
  password: process.env.TYPEORM_PASSWORD,
  database: process.env.TYPEORM_DATABASE
});

appDataSource.initialize()
  .then(() => {
    console.log('Data Source has been initialized!');
  })
  .catch((err) => {
    console.error('Error occurred during Data Source initialization', err);
    appDataSource.destroy();
  });
  
  module.exports = { appDataSource }
```

2022-10-13 02:31 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-10-13 02:31 UTC, merged