[박은송-teamB] Assignment 1: Error Handling
wecode-bootcamp-korea/38-backend-westagram pull request #59
Opened 2022-10-11 13:58 UTC by Eunsong-Park

## 수정 사항 간략한 한줄 요약
- 에러 핸들링 기능 추가
		 
## 수정 사항들 자세한 내용
- 이메일 중복 확인 기능 추가
중복 시 status code : 400, message : DUPLICATE_EMAIL 반환

- 이메일 형식 검사 기능 추가
형식에 안 맞을 시 status code : 400, message : EMAIL_ADDRESS_IS_NOT_VALID 반환

- 회원가입 요청 (이름 / 이메일 / 비밀번호 / 프로필 이미지) 유효성 검사 추가
오류 시 status code : 400, message KEY_ERROR 반환

- Post 수정 요청 (제목 / 내용) 유효성 검사 추가
오류 시 status code : 400, message KEY_ERROR 반환

- Post 업로드 요청 (제목 / 내용 / 유저 id / 포스팅 이미지) 유효성 검사 추가
오류 시 status code : 400, message KEY_ERROR 반환

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-11 14:04 UTC, Eunsong-Park commented
![스크린샷 2022-10-11 오후 11 00 16](https://user-images.githubusercontent.com/111448985/195112857-862fc25e-c5d1-47a9-b12a-6faf170b665c.png)
![스크린샷 2022-10-11 오후 11 00 55](https://user-images.githubusercontent.com/111448985/195112881-c402136d-f797-41f2-820a-da4f1d244b0b.png)
![스크린샷 2022-10-11 오후 11 01 26](https://user-images.githubusercontent.com/111448985/195112892-2faa549d-463c-4b7c-815a-bc156829ae20.png)
![스크린샷 2022-10-11 오후 11 02 15](https://user-images.githubusercontent.com/111448985/195112911-3945f774-195b-49ef-914e-7fd5a911e9ab.png)
![스크린샷 2022-10-11 오후 11 03 04](https://user-images.githubusercontent.com/111448985/195112930-6388ce52-9b00-4cb2-96c2-b0317b1526fe.png)

2022-10-12 02:16 UTC, SeongJoon-K requested changes

2022-10-12 02:16 UTC, SeongJoon-K commented on teamB/eunsong/routes/index.js
> +router.use("/likes", likeRouter.router);
- 해당 부분은 코드 가독성을 위해 한 줄 띄어서 작성해 주세요 !
```suggestion
const likeRouter = require("./likeRouter");

router.use("/users", userRouter.router);
router.use("/posts", postRouter.router);
router.use("/likes", likeRouter.router);
```

2022-10-12 04:54 UTC, Eunsong-Park commented on teamB/eunsong/routes/index.js
> +router.use("/likes", likeRouter.router);
네 한줄 띄어서 다시 push 하겠습니다!

2022-10-12 05:38 UTC, SeongJoon-K approved these changes

2022-10-12 05:38 UTC, merged