[김성훈-teamB] Assignment 4: Layered Pattern
wecode-bootcamp-korea/38-backend-westagram pull request #60
Opened 2022-10-11 13:59 UTC by Hey-Hello-World

## 작업내역
- 유저 회원가입 하기
- 게시글 등록하기
- 전체 게시글 조회하기
- 유저의 게시글 조회하기
- 게시글 수정하기
- 게시글 삭제하기
- 좋아요 누르기
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-12 02:21 UTC, SeongJoon-K requested changes
성훈님 ! schema.sql 파일이 github상에 관리되고 있습니다 !
해당 부분은 gitignore에 작성하여 github상에 업로드 되면 안됩니다 !
수정부탁드립니다 ~!

2022-10-12 02:21 UTC, SeongJoon-K commented on teamB/kimSungHoon/controllers/postController.js
> +}
- 해당 부분 indentation을 수정해주세요 !
```suggestion
module.exports = {
    createPost,
    readingPost,
    updatePost,
    deletePost
}
```

2022-10-12 02:21 UTC, SeongJoon-K commented on teamB/kimSungHoon/controllers/userController.js
> +}
- 해당 부분도 indentation을 지켜주세요 !
```suggestion
module.exports = {
    signUp,
    userPosting,
    like
}
```

2022-10-12 05:03 UTC, Hey-Hello-World commented on teamB/kimSungHoon/controllers/userController.js
> +}
원본 파일에 indentation을 지켜서 올렸는데 github 상에서는 들여쓰기가 되어있는 것으로 나옵니다... 그리고 git 업을 해도 수정이 안되는 상황입니다. 위에 말씀해주신 부분도 동일합니다.

2022-10-12 07:14 UTC, sangwoong03 reviewed
성훈님! 들여쓰기 수정이 안된다면, 줄바꿈을 하지 않은 상태에서 다시 줄바꿈을 시도해주세요!

github상에서 바로 수정하면 원격의 코드 버전과 로컬의 코드 버전이 달라 conflict가 발생할 것입니다!

확인 후 제한사항 생기면 말씀해주세요~!

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/routes/index.js
> +router.use('/posts', postRouter.router);
가독성을 위해 모듈을 불러오는 부분과 모듈 동작에 필요한 프로퍼티를 추가하는 부분을 분리해주세요!
```suggestion
const userRouter = require('./userRouter');
const postRouter = require('./postRouter');

router.use('/users', userRouter.router);
router.use('/posts', postRouter.router);
```

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/routes/postRouter.js
> +router.delete('/delete/:postId', postController.deletePost);
추후 RESTful API 세션을 통해 배울 내용입니다만 RESTful API에서 엔드포인트를 구성할 땐 동사가 아닌 명사로 작성하게 됩니다. 또한 해당 메서드가 엔드포인트로 드러나지 않게 수정해주세요!

routes/index.js 파일에서 postRouter로 이동할 때의 url이 `/posts`인 것을 고려하여 다음과 같이 작성해줍니다.

엔드포인트 요청 시 url은 다음과 같습니다.
`http://localhost:3000/posts` (get)
`http://localhost:3000/posts/1` (patch)

```suggestion
router.post('/', postController.createPost);
router.get('/', postController.readingPost);
router.patch('/:postId', postController.updatePost);
router.delete('/:postId', postController.deletePost);
```

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/routes/userRouter.js
> +router.post('/like', userController.like);
추후 RESTful API 세션을 통해 배울 내용입니다만 RESTful API에서 엔드포인트를 구성할 땐 동사가 아닌 명사로 작성하게 됩니다. 또한 해당 메서드가 엔드포인트로 드러나지 않게 수정해주세요!

routes/index.js 파일에서 postRouter로 이동할 때의 url이 /posts인 것을 고려하여 다음과 같이 작성해줍니다.

엔드포인트 요청 시 url은 다음과 같습니다.
http://localhost:3000/users/signup (post)
http://localhost:3000/users/signin (post)

또한 posts 데이터를 받아오는 엔드포인트는 postRouter.js 파일로 옮겨주세요!

좋아요 기능을 위해 필요한 추가 기능이 있습니다. 확인 후 추가해주세요!
 
```suggestion
router.post('/signup', userController.signUp);
router.post('/signin', userController.signUp); // 추가 예시
```

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/services/userService.js
> +    const pwValidation = new RegExp(
문자열을 변수에 할당할 때엔 변수를 대문자로 작성하는 컨벤션이 있습니다.

```suggestion
    const PASSWORD_REGEX = new RegExp(
```

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/db/migrations/20221007111253_create_likes_table.sql
> +);
좋아요 기능을 구현할 때에는 주의해야할 점이 있습니다.
하나의 사용자가 하나의 게시물에 대해서 좋아요를 할 수 있는 횟수는 단 한 번 이어야 합니다.
지금 구조에서는 좋아요를 누를 때마다 아래와 같이 likes 테이블에 계속해서 중복으로 데이터가 저장됩니다.
    
    ```sql
    +----+---------+---------+---------------------+
    | id | user_id | post_id | created_at          |
    +----+---------+---------+---------------------+
    |  1 |       1 |       3 | 2022-07-16 14:18:26 |
    |  2 |       1 |       3 | 2022-07-16 14:18:26 |
    |  3 |       1 |       3 | 2022-07-16 14:18:26 |
    |  4 |       1 |       3 | 2022-07-16 14:18:26 |
    |  5 |       1 |       3 | 2022-07-16 14:18:47 |
    |  6 |       1 |       3 | 2022-07-16 14:18:47 |
    +----+---------+---------+---------------------+
    ```
    
이를 막기 위해서, likes 테이블에 user_id와 post_id를 기준으로 UNIQUE 제약조건을 추가하는 migration 파일을 추가로 만들어서 올려주세요.

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/models/postDao.js
> +// const { deletePost } = require('../services/postService');
불필요한 주석은 삭제해주세요!

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/models/userDao.js
> +}
해당 코드는 posts 테이블에서 참조하고 있는 유저 정보를 확인하여 특정 게시글을 받아올 때 사용할 수 있을 것 같습니다.

userId를 클라이언트로부터 받아 posts 테이블의 user_id와 일치 여부를 확인 후 일치하는 posts 데이터를 반환해주세요!

2022-10-12 07:14 UTC, sangwoong03 commented on teamB/kimSungHoon/models/userDao.js
> +}
likes와 관련된 router - controller - service - model 모듈을 분리할 수 있을 것 같습니다.

분리 후 다시 push해주세요!

2022-10-12 08:44 UTC, Hey-Hello-World commented on teamB/kimSungHoon/models/postDao.js
> +// const { deletePost } = require('../services/postService');
수정완료 했습니다.

2022-10-12 08:46 UTC, Hey-Hello-World commented on teamB/kimSungHoon/routes/index.js
> +router.use('/posts', postRouter.router);
수정완료 했습니다.

2022-10-12 09:00 UTC, Hey-Hello-World commented on teamB/kimSungHoon/services/userService.js
> +    const pwValidation = new RegExp(
수정 완료했습니다.

2022-10-12 11:31 UTC, Hey-Hello-World commented on teamB/kimSungHoon/controllers/postController.js
> +}
수정완료 했습니다 !

2022-10-12 11:46 UTC, Hey-Hello-World commented on teamB/kimSungHoon/routes/postRouter.js
> +router.delete('/delete/:postId', postController.deletePost);
감사합니다 수정완료 했습니다.

2022-10-12 11:58 UTC, Hey-Hello-World commented on teamB/kimSungHoon/models/userDao.js
> +}
감사합니다 수정완료 했습니다.

2022-10-12 12:34 UTC, Hey-Hello-World commented on teamB/kimSungHoon/db/migrations/20221007111253_create_likes_table.sql
> +);
감사합니다 수정완료 했습니다.

2022-10-12 13:16 UTC, Hey-Hello-World commented on teamB/kimSungHoon/models/userDao.js
> +}
감사합니다 수정완료 했습니다.

2022-10-14 01:00 UTC, sangwoong03 reviewed
성훈님! 고생하셨습니다.

14일 오전 기준으로도 아직 git 문제가 해결되지 않으신 건가요?

2022-10-14 01:00 UTC, sangwoong03 commented on teamB/kimSungHoon/controllers/postController.js
> +        return res.status(201).json({ "message" : "postingDeleted" });
delete 메서드를 통해 데이터 삭제를 성공했을 때의 status code에 대해 다시 한 번 생각해주세요~!

http status code로 검색했을 때에도 다양한 자료가 나오니 참고해주세요!

2022-10-14 01:00 UTC, sangwoong03 commented on teamB/kimSungHoon/controllers/userController.js
> +        return res.status(201).json({ data: result });
이 부분도 마찬가지로 클라이언트에게 보여지는 status code를 작성하는 부분입니다.

http status code에 대한 다양한 자료를 접해주세요!

2022-10-14 01:00 UTC, sangwoong03 commented on teamB/kimSungHoon/models/likeDao.js
> +    })
성훈님~! 해당 부분이 Dao 파일 내부에서 반복되고 있습니다.

반복되는 작업을 피하면서 유지보수 측면에도 유리할 수 있도록 하나의 모듈로 따로 분리하여 주세요!

2022-10-14 01:00 UTC, sangwoong03 commented on teamB/kimSungHoon/services/userService.js
> +        err.statusCode = 409;
이 부분에서 409 상태메시지를 반환하는 이유가 무엇인가요?

2022-10-14 01:15 UTC, Hey-Hello-World commented
> 성훈님! 고생하셨습니다.
> 
> 14일 오전 기준으로도 아직 git 문제가 해결되지 않으신 건가요?

2022-10-14 01:16 UTC, Hey-Hello-World commented on teamB/kimSungHoon/controllers/postController.js
> +        return res.status(201).json({ "message" : "postingDeleted" });
감사합니다 delect 요청으로 삭제 시 제가 삭제된 것을 확인하기 위해 201 코드 및 메세지 출력을 설정해놓았는데 멘토님 말씀듣고 검색하여  더 알맞는 코드를 선택할 수 있어서 수정완료하였습니다 감사합니다.

2022-10-14 04:28 UTC, Hey-Hello-World commented on teamB/kimSungHoon/models/likeDao.js
> +    })
감사합니다 수정 완료하였습니다.

2022-10-14 04:32 UTC, Hey-Hello-World commented on teamB/kimSungHoon/controllers/userController.js
> +        return res.status(201).json({ data: result });
감사합니다 수정완료 하였습니다.

2022-10-14 04:34 UTC, Hey-Hello-World commented on teamB/kimSungHoon/services/userService.js
> +        err.statusCode = 409;
400을 409로 착각한 것 같습니다. http status code 통해서 400으로 수정했습니다.  감사합니다

2022-10-14 09:42 UTC, SeongJoon-K requested changes
성훈님 ! 너무 고생하셨습니다 ! 요청한 부분 수정해서 다시 커밋 부탁드려요 ~!

2022-10-14 09:42 UTC, SeongJoon-K commented on teamB/kimSungHoon/.env.sample
>  PORT = your port number should be here !
성훈님 .env.sample 의 내용을 채워서 수정해주세요 !

2022-10-14 09:42 UTC, SeongJoon-K commented on teamB/kimSungHoon/controllers/postController.js
> +    	deletePost
indentation 맞춰서 수정해주세요 !
```suggestion
	createPost,
    	readingPost,
    	updatePost,
    	deletePost
```

2022-10-14 09:42 UTC, SeongJoon-K commented on teamB/kimSungHoon/routes/postRouter.js
> +router.delete('/:postId', postController.deletePost);
해당 부분은 코드의 길이가 길어 보일 수 있어 아래와 같이 수정해주세요 !
```suggestion
router.post('/', postController.createPost);
router.get('/', postController.readingPost);
router.patch('/:postId', postController.updatePost);
router.delete('/:postId', postController.deletePost);
```

2022-10-14 12:48 UTC, Hey-Hello-World commented on teamB/kimSungHoon/.env.sample
>  PORT = your port number should be here !
username 부분을 혹시 root로 수정하시라는 말씀이신가요 ? 127.0.0.1은 ip로 변경하였으며 username은 root로 변경하겠습니다 감사합니다

2022-10-14 12:51 UTC, Hey-Hello-World commented on teamB/kimSungHoon/controllers/postController.js
> +    	deletePost
vscode 상에서는 정상적으로 되어있어서 왜 이런지 모르겠습니다.. 일단 기존 vscode 에서 createPost는 안쪽으로 들여쓰기 하겠습니다.

2022-10-14 12:51 UTC, Hey-Hello-World commented on teamB/kimSungHoon/routes/postRouter.js
> +router.delete('/:postId', postController.deletePost);
감사합니다 수정하였습니다.

2022-10-15 13:35 UTC, SeongJoon-K approved these changes

2022-10-15 13:35 UTC, merged