[신인혁-teamB] Assignment 1: Express API - 초기 환경 세팅
wecode-bootcamp-korea/38-backend-westagram pull request #8
Opened 2022-10-06 04:42 UTC by ShinInHuck

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-10-06 05:18 UTC, kyeongraekim requested changes

2022-10-06 05:18 UTC, kyeongraekim commented on teamB/shinInHuck/myapp/app.js
> +dotenv.config()
- import 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 이런 컨벤션 준수들이 모여서 좀 더 가독성 좋은 코드가 됩니다.
- 가독성을 위해서 환경변수 설정에 필요한 ‘dotenv’ 모듈을 `require('dotenv').config();`과 같이 최상단에 불러옵니다.
- 이후 라이브러리는 다음과 같은 순서로 import 해줍니다.
    - bulit-in 패키지
    - 3rd-party 패키지
    - custom 패키지
```javascript
// Example
require('dotenv').config();

// Built-in package
const http = require('http')

// 3rd-party package
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();

2022-10-06 05:18 UTC, kyeongraekim commented on teamB/shinInHuck/myapp/app.js
> +const myDataSource = new DataSource({
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- DataSource.initialize() 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.
- 추후 에러 핸들링을 담을 때의 가독성 및 확장성 보장을 위해 ".then"을 (typeorm datasource 공식문서에서 제안하는 것 처럼) 한칸 아래로 띄는 것을 권장드립니다.
- 참고 링크: [https://typeorm.biunav.com/en/data-source.html#what-is-datasource](https://typeorm.biunav.com/en/data-source.html#what-is-datasource)

2022-10-06 05:19 UTC, kyeongraekim requested changes

2022-10-06 05:19 UTC, kyeongraekim commented on teamB/shinInHuck/myapp/app.js
> +// });
main 브랜치에 merge 목적으로 올리는 코드에는 불필요한 주석문이 없어야 합니다. 아래 27~29번 째라인의 동일 기능을하는 코드 중 어느 것을 의도하여 남기고 싶으신지 양자택일을 하여 푸시해주세요.

2022-10-09 08:20 UTC, SeongJoon-K requested changes

2022-10-09 08:20 UTC, SeongJoon-K commented on teamB/shinInHuck/myapp/.env.sample
> +TYPEORM_LOGGING =TRUE
- 배포 및 상용화의 목적으로 Github main 브랜치에 올리는 코드에 서버의 다양한 기록들을 확인해볼 수 있는 기능인 logging 이 True가 되어 있어서는 안됩니다. 해당 내용은 삭제하거나 false로 수정해주세요 !
- 더불어 .env.sample의 경우 타인이 해당 서버를 사용할 때 설명과 같은 역할을 하기 때문에 어떤 것을 넣을지 이해할 수 있도록 YOUR NAME등 과 같은 설명이 들어가야합니다.

```suggestion
TYPEORM_CONNECTION = mysql
TYPEORM_HOST = 127.0.0.1
TYPEORM_USERNAME = YOUR NAME
TYPEORM_PASSWORD = YOUR PW
TYPEORM_DATABASE = YOUR DB
TYPEORM_PORT = 3306
TYPEORM_LOGGING =TRUE 
```

2022-10-09 08:20 UTC, SeongJoon-K commented on teamB/shinInHuck/myapp/app.js
> +})
- 구현되지 않은 코드는 test 파일상 혹은 로컬 repo에만 존재하고, remote repo에는 동작가능한 코드만 존재해야합니다. 해당 부분을 수정해주세요 !
```suggestion
```

2022-10-11 06:03 UTC, closed without merging